name: Run Tests 

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install mxeval
      run: |
        git clone https://github.com/amazon-science/mxeval.git
        pip install -e mxeval
    - name: Store DFA mask in cache
      uses: actions/cache@v3
      with:
          path: cache/
          key: files-${{ hashFiles('syncode/parsers/grammars/python_grammar.lark', 'syncode/dfa_mask_store.py') }}
    - name: Run Tests
      run: |
        python syncode/tests/test_grammar_python.py
        python syncode/tests/test_grammar_go.py
        python syncode/tests/test_calc.py
        python syncode/tests/test_lr_parser.py
        python syncode/tests/test_language_model.py
        python syncode/tests/test_syncode.py
        python syncode/tests/test_dfa_mask_python.py --independent
