name: Tests 

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
          path: /home/runner/.cache/pip/
          key: files-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache DFA mask store
      uses: actions/cache@v3
      with:
          path: /home/runner/work/syncode/syncode/cache/mask_stores/
          key: files-${{ hashFiles('syncode/parsers/grammars/python_grammar.lark', 'syncode/dfa_mask_store.py') }}
    - name: Run Tests
      run: |
          python3 -m unittest tests.test_misc
          python3 -m unittest tests.test_grammar_go
          python3 -m unittest tests.test_grammar_sql
          python3 -m unittest tests.test_grammar_python
          python3 -m unittest tests.test_grammar_json
          python3 -m unittest tests.test_grammar_java
          python3 -m unittest tests.test_language_model
          python3 -m unittest tests.test_lr_parser
          python3 -m unittest tests.test_syncode
