name: Run Tests 

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
          path: /home/runner/.cache/pip/
          key: files-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install mxeval
      run: |
        git clone https://github.com/amazon-science/mxeval.git
        pip install -e mxeval
    - name: Cache DFA mask store
      uses: actions/cache@v3
      with:
          path: /home/runner/work/syncode/syncode/cache/mask_stores/
          key: files-${{ hashFiles('syncode/parsers/grammars/python_grammar.lark', 'syncode/dfa_mask_store.py') }}
    - name: Run Tests
      env:
        PYTHONPATH: ${{ github.workspace }} /syncode
      run: |
          python -m unittest discover -s tests
